export const amberAlertType = {
  GET_ALL_AMBER_ALERT_REQUSERT_SECCESS: "GET_ALL_AMBER_ALERT_REQUEST_SECCESS",
  GET_AMBER_ALERT_DATA_BY_ALERT_ID: "GET_AMBER_ALERT_DATA_BY_ALERT_ID",
  RESPONSE_TO_AMBER_BY_USERS: "RESPONSE_TO_AMBER_BY_USERS"
};