export const loginType = {
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    CONFIRM_OTP_SUCCESS:"CONFIRM_OTP_SUCCESS",
    CONFIRM_OTP_FAILURE:"CONFIRM_OTP_FAILURE",
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SECCESS:'LOGOUT_SECCESS',
}