export const liveRequestType ={
    GET_ALL_LIVE_REQUEST_SECCESS:"GET_ALL_LIVE_REQUEST_SECCESS",
    GET_ALL_LIVE_REQUEST_FAILURE:"GET_ALL_LIVE_REQUEST_FAILURE"
}

export const completLiveRequestType ={
    GET_COMPLET_ALL_LIVE_REQUEST_SECCESS:"GET_COMPLET_ALL_LIVE_REQUEST_SECCESS",
    GET_ALL_LIVE_REQUEST_FAILURE:"GET_ALL_LIVE_REQUEST_FAILURE"
}