export const otherServiceTypes = {
    GET_ALL_OTHER_SERVICE_REQUEST_SECCESS: "GET_ALL_OTHER_SERVICE_REQUEST_SECCESS",
    GET_ALL_OTHER_SERVICE_REQUEST_FAILURE: "GET_ALL_OTHER_SERVICE_REQUEST_FAILURE",
    GET_ALL_OTHER_SERVICE_REQUEST_DETAIL: "GET_ALL_OTHER_SERVICE_REQUEST_DETAIL",
}