export const ServiceType = {
    GET_ALL_SERVICE_SUCCESS: "GET_ALL_SERVICE_SUCCESS",
    GET_ALL_SERVICE_FAILURE: "GET_ALL_SERVICE_FAILURE",
    GET_ALL_SERVICE_DATA_BY_SERVICE_ID_SUCCESS: "GET_ALL_SERVICE_DATA_BY_SERVICE_ID_SUCCESS",
    GET_ONE_HELP_REQUEST_DATA_SECCESS: "GET_ONE_HELP_REQUEST_DATA_SECCESS",
    ADD_RESOURSES: "ADD_RESOURSES",
    REMOVE_RESOURSE: 'REMOVE_RESOURSE'
    // GET_BY_ID_ALL_SERVICE_SUCCESS:"GET_BY_ID_ALL_SERVICE_SUCCESS",
    // GET_BY_ID_ALL_SERVICE_FAILURE:"GET_BY_ID_ALL_SERVICE_FAILURE"
}