export const UserType = {
    GET_ALL_USER_SUCCESS:"GET_ALL_USER_SUCCESS",
    GET_ALL_USER_FAILURE:"GET_ALL_USER_FAILURE",
    GET_USER_BY_ID_SUCCESS:"GET_USER_BY_ID_SUCCESS",
    GET_USER_BY_ID_FAILURE:"GET_USER_BY_ID_FAILURE",
    GET_ALL_USER_ADDED_BY_ADMIN_SUCCESS:"GET_ALL_USER_ADDED_BY_ADMIN_SUCCESS",
    DOCUMENT_VERIFY_SUCCESS:"DOCUMENT_VERIFY_SUCCESS",
    STATUS_CHANGE:"STATUS_CHANGE"
}
    